/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class redlaboratory_globalinputmanager_GlobalHook */

#ifndef _Included_redlaboratory_globalinputmanager_GlobalHook
#define _Included_redlaboratory_globalinputmanager_GlobalHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     redlaboratory_globalinputmanager_GlobalHook
 * Method:    enable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_redlaboratory_globalinputmanager_GlobalHook_enable
  (JNIEnv *, jclass);

/*
 * Class:     redlaboratory_globalinputmanager_GlobalHook
 * Method:    disable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_redlaboratory_globalinputmanager_GlobalHook_disable
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
