/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class redlaboratory_globalinputmanager_GlobalInput */

#ifndef _Included_redlaboratory_globalinputmanager_GlobalInput
#define _Included_redlaboratory_globalinputmanager_GlobalInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     redlaboratory_globalinputmanager_GlobalInput
 * Method:    typeString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_redlaboratory_globalinputmanager_GlobalInput_typeString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
